# Generated by Django 2.0 on 2023-07-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('createdTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedTime', models.DateTimeField(auto_now=True, null=True)),
                ('deletedTime', models.DateTimeField(default=None, null=True)),
                ('blob', models.ImageField(upload_to='grocery/inventoryimg/')),
            ],
        ),
    ]
