# Generated by Django 2.1 on 2023-08-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blob',
            field=models.ImageField(upload_to='onestop/grocery/inventory/'),
        ),
    ]
