# Generated by Django 2.1 on 2023-08-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20230813_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default=None, upload_to='onestop/grocery/inventory/'),
        ),
    ]
