# Generated by Django 2.1 on 2023-08-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blob',
            field=models.ImageField(upload_to='onestop'),
        ),
    ]
