# Generated by Django 2.1 on 2023-08-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20230816_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blob',
            field=models.ImageField(upload_to=''),
        ),
    ]
