# Generated by Django 2.1 on 2023-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20230816_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='blob',
            field=models.ImageField(upload_to=''),
        ),
    ]
